name: Application CI
on: [push, pull_request]
jobs:
  pipeline:
    name: Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 20
          cache: 'gradle'
      - name: test
        run: ./gradlew spotlessApply check --no-daemon
      - name: build
        run: ./gradlew install --no-daemon